### PR TITLE
fix crash when attempt to delete while idle

### PR DESCRIPTION
**Pull request by dyphire**
Also avoids attempt to delete network files.

### CODE REVIEW

**Comment by stax76** [comment]
I usually check only if `://` is contained, but am not sure if it's sufficient.

**Comment by dyphire** [comment]
> I usually check only if `://` is contained, but am not sure if it's sufficient.

Some URL protocols do not have slashes, such as `magnet:?`.

**Comment by stax76** [comment]
If I understand correctly, the dash in the brackets does not define a range, but is meant to match a dash, to make this more clear the dash can be moved to first or last position.

**Comment by stax76** [comment]
`if pos >= 0 then mp.command("playlist-remove " .. pos) end`

Shouldn't this be `> -1` because 0 is the first file and can be deleted?

**Comment by dyphire** [comment]
> If I understand correctly, the hyphen (minus sign) in the square brackets does not define a range, but is meant to match a hyphen, to make this more clear the dash can be moved to first or last position.

Done.

**Comment by stax76** [comment]
```Lua
path:match('^%a[%a%d-_]+:\\?')
```

Can you post an example for it?

**Comment by dyphire** [comment]
> ```lua
> path:match('^%a[%a%d-_]+:\\?')
> ```
> 
> Can you post an example link for it?

Any magnet links. For example, you can find it here: https://nyaa.si/
You may also need to use the script of [mpv-webtorrent-hook](https://github.com/noctuid/mpv-webtorrent-hook) or [mpv-btfs-stream](https://github.com/noctuid/mpv-btfs-stream) to allows mpv to stream magnet links.

**Comment by stax76** [comment]
`:\\?`

This means maybe there is one backslash after a colon, right? So URL's containing backslashes are possible?

**Comment by dyphire** [comment]
> `:\\?`
> 
> This means maybe there is a backslash after a colon, right? So URL's containing backslashes are possible?

This code is stolen from https://github.com/tomasklaen/uosc/pull/336. To be honest, I also don't know the scenario where URL's contain backslashes.

**Pull request merged**
