### PR TITLE
optimization and enhancement

### PR DESCRIPTION
**Pull request by dyphire**
add uosc script compatibility
add mouse control support
make palette scale based on OSD window size

### CODE REVIEW

**Comment by stax76** [comment]
I rewrote this now, please let me know what you think.

https://github.com/stax76/mpv-scripts/commit/1632998ad900934108eded37498e892032803a27

**Comment by dyphire** [comment]
> I rewrote this now, please let me know what you think: [1632998](https://github.com/stax76/mpv-scripts/commit/1632998ad900934108eded37498e892032803a27)

After reviewing the commit, I don't think you know much about libass 'scaling behavior, so let me explain in a rough way: libass scales to the target resolution based on PlayRes* and the specified font size, and when the font size and PlayRes* don't match, it causes scaling errors.

In this script, the resolution of the osd window is the PlayRes* required by libass, and to get the correct scaling, you need to pass the correct font size. This is why display-width is not available, because the default font size you specify will not correspond correctly to the value PlayResX uses for display-width, which will result in incorrect scaling of libass.

**Comment by dyphire** [comment]
Of course, different OSD fonts are also different from the default font size of the preset 1920 PlayResX due to their different glyph sizes. I ignored this point, and it is a good idea to add the font options back.

**Comment by stax76** [comment]
Thanks for the detailed explanation, I appreciate it. Is it better with the last commit?

**Comment by dyphire** [comment]
> Thanks for the detailed explanation, I appreciate it. Is it better with the last commit?

I'm curious what the point of the scale_with_osd_size option existing is?

**Pull request merged**
